# Generated by Django 6.0.1 on 2026-03-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('amenidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('icono_nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('categoria', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amenidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Divisa',
            fields=[
                ('divisa_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('acronimo', models.TextField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'divisa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('favorito_id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'favorito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('propiedad_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('pais', models.CharField(max_length=25)),
                ('ciudad', models.CharField(max_length=25)),
                ('direccion', models.CharField(max_length=100)),
                ('activa', models.IntegerField(blank=True, null=True)),
                ('coordenadas', models.JSONField()),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_huespedes', models.IntegerField()),
                ('habitaciones', models.IntegerField()),
                ('camas', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('check_in', models.TimeField()),
                ('check_out', models.TimeField()),
                ('regla_mascotas', models.IntegerField()),
                ('regla_ninos', models.IntegerField()),
                ('regla_fumar', models.IntegerField()),
                ('regla_fiestas', models.IntegerField()),
                ('regla_autochecar', models.IntegerField()),
                ('regla_apagar', models.IntegerField()),
                ('reglas_extra', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'propiedad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropiedadImagen',
            fields=[
                ('prop_ima_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('orden', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('updated_by', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'propiedad_imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPropiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'tipo_propiedad',
                'managed': False,
            },
        ),
    ]
