# Generated by Django 6.0.1 on 2026-03-09 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenidad',
            options={'managed': False, 'ordering': ['categoria']},
        ),
    ]
