# Generated by Django 6.0.1 on 2026-03-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0002_alter_amenidad_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasAmenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorias', models.TextField(db_collation='utf8mb4_0900_ai_ci')),
            ],
            options={
                'db_table': 'categorias_amenidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PropiedadCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('propiedad_id', models.IntegerField()),
                ('titulo', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=50)),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ciudad', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=25)),
                ('pais', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=25)),
                ('divisa', models.TextField(db_collation='utf8mb4_0900_ai_ci')),
                ('tipo_propiedad', models.TextField(db_collation='utf8mb4_0900_ai_ci')),
                ('imagen_principal', models.TextField(blank=True, db_collation='utf8mb4_0900_ai_ci', null=True)),
            ],
            options={
                'db_table': 'propiedad_card',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=25)),
                ('pais', models.CharField(db_collation='utf8mb4_0900_ai_ci', max_length=25)),
            ],
            options={
                'db_table': 'ubicaciones',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='divisa',
            options={'managed': False, 'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='propiedadimagen',
            options={'managed': True, 'ordering': ['orden']},
        ),
        migrations.AlterModelOptions(
            name='tipopropiedad',
            options={'managed': False, 'ordering': ['tipo']},
        ),
    ]
