# Generated by Django 6.0.1 on 2026-03-09 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0003_categoriasamenidad_propiedadcard_ubicaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedadimagen',
            options={'managed': False, 'ordering': ['orden']},
        ),
    ]
