# Generated by Django 6.0.1 on 2026-03-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propiedades', '0005_alter_propiedad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propiedad',
            options={'managed': False},
        ),
    ]
